### ISSUE TITLE
Deep Dark Portal

### ISSUE THREAD

**Issue by Yabdat** [avidgamer5918/Staged-Learning#8]
If you try to teleport into the Deep Dark it crashes the server instantly (dedicated server).
Step on portal, wavy animantion, servercrash.

Crashreport: https://pastebin.com/Fmi1s71s

**Comment by avidgamer5918** [comment]
I disabled the deep dark because it has no way to configure what ores spawn in it. It was breaking progression by spawning in ores that you are not supposed to be able to get tin the pack. I thought I thought I disabled the recipe for the portal but I must of forgot. This will be fixed in the next update. Thank you for reporting
